=== iiRays/gloryflorist/Controllers/FlowerXML/Flower.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!--
 Author: Chong Wei Jie
 ID: 19WMR09574
-->
<!ELEMENT flowers (flower*)>
<!ELEMENT flower (id, flower_name, remark, img, is_available)>
<!ATTLIST flower id ID #REQUIRED>

<!ELEMENT id (#PCDATA)>
<!ELEMENT flower_name (#PCDATA)>
<!ELEMENT remark (#PCDATA)>
<!ELEMENT img (#PCDATA)>
<!ELEMENT is_available (#PCDATA)>

=== iiRays/gloryflorist/Controllers/FlowerXML/Flower.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Flower.xsl"?><!DOCTYPE flowers SYSTEM 'Flower.dtd'><flowers>
    <flower id="1">
        <id>1</id>
        <flower_name>Rose</flower_name>
        <remark>Very beautiful</remark>
        <img>https://i.imgur.com/yd4JiYF.png</img>
        <is_available>true</is_available>
    </flower>
    <flower id="2">
        <id>2</id>
        <flower_name>Lily</flower_name>
        <remark>Very beautiful</remark>
        <img>https://i.imgur.com/yd4JiYF.png</img>
        <is_available>false</is_available>
    </flower>
</flowers>
